---
- hosts: localhost
  become: yes
  tasks:
   -  name: create a ansible ubuntu node
      ec2:
       key_name: new2
       instance_type: t2.micro
       image: ami-0a57745ac441f483b
       wait: yes     
       count: 1
       region: us-east-2
       group: mysg
       vpc_subnet_id: subnet-0948396a1ab39c95d
       assign_public_ip: yes
       instance_tags:
         Name: ansiblenode      
