---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want install webserver on ubuntu node
    apt:
     name: apache2
     state: present

  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      name: tree
      state: present
  - name: install wget
    apt:
      name: wget
      state: present

  - name: install httpd
    yum:
      name: httpd
      state: present 
    when: ansible_os_family == "RedHat"   