---
 - name: download tomcat
   get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.48/bin/apache-tomcat-9.0.48.tar.gz
     dest: /home/ubuntu/apache-tomcat-9.0.48.tar.gz
     force_basic_auth: yes
 - name: create folder
   file:
    path: /opt/tomcat
    state: directory    
 - name: extract tomcat tar file
   command:
     cmd: tar xzvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
     creates: /opt/tomcat/LICENSE